=== yifengyou/pungi/BUILD/pungi-4.3.6/share/variants.dtd
<!ELEMENT variants (ref*,variant*)>

<!ELEMENT variant (release?,arches,groups?,environments*,variants*,buildinstallpackages?,modules?)?>
<!ATTLIST variant
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    type (variant|addon|optional|layered-product) #REQUIRED
    has_optional (true|false) #IMPLIED
    is_empty (true|false) "false"
>

<!ELEMENT release (#PCDATA)>
<!ATTLIST release
    name CDATA #IMPLIED
    short CDATA #IMPLIED
    version CDATA #IMPLIED
>

<!ELEMENT arches (arch)+>

<!ELEMENT groups (group)+>

<!ELEMENT group (#PCDATA)>
<!ATTLIST group
    glob (true|false) #IMPLIED
    default (true|false) #IMPLIED
    uservisible (true|false) #IMPLIED
>

<!ELEMENT modules (module*, kojitag*)>

<!ELEMENT module (#PCDATA)>
<!ELEMENT kojitag (#PCDATA)>
<!ATTLIST module
    glob (true|false) #IMPLIED
>

<!ELEMENT environments (environment)+>

<!ELEMENT environment (#PCDATA)>
<!ATTLIST environment
    display_order CDATA #IMPLIED
>

<!ELEMENT arch (#PCDATA)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT ref EMPTY>
<!ATTLIST ref
    id CDATA #REQUIRED
>

<!ELEMENT buildinstallpackages (package)+>
<!ELEMENT package (#PCDATA)>

=== yifengyou/pungi/BUILD/pungi-4.1.38/tests/data/multi-compose-variants.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variants PUBLIC "-//Red Hat, Inc.//DTD Variants info//EN" "variants.dtd">

<variants>
  <variant id="ResilientStorage" name="Resilient Storage" type="variant">
    <arches>
      <arch>x86_64</arch>
    </arches>
    <groups>
      <group default="true">resilient-storage</group>
    </groups>
  </variant>

  <variant id="Client" name="Client" type="variant">
    <arches>
      <arch>i386</arch>
      <arch>x86_64</arch>
    </arches>
    <groups>
      <group default="true">core</group>
      <group default="true">standard</group>
      <group default="false">text-internet</group>
      <group default="true" uservisible="false">firefox</group>
      <group>skype</group>
    </groups>
    <environments>
      <environment>minimal</environment>
      <environment display_order="1000">desktop</environment>
    </environments>
  </variant>

  <variant id="Server" name="Server" type="variant">
    <arches>
      <arch>x86_64</arch>
      <arch>s390x</arch>
    </arches>
    <groups>
      <group default="true" uservisible="true">core</group>
      <group default="true">standard</group>
      <group default="true">text-internet</group>
    </groups>
    <environments>
      <environment>minimal</environment>
    </environments>
  </variant>

</variants>

=== yifengyou/pungi/BUILD/pungi-4.1.38/tests/fixtures/variants.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variants PUBLIC "-//Red Hat, Inc.//DTD Variants info//EN" "variants.dtd">

<variants>
  <variant id="ResilientStorage" name="Resilient Storage" type="addon">
    <arches>
      <arch>x86_64</arch>
    </arches>
    <groups>
      <group default="true">resilient-storage</group>
    </groups>
  </variant>

  <variant id="Live" name="Live" type="variant" is_empty="true">
    <arches>
      <arch>x86_64</arch>
    </arches>
  </variant>

  <variant id="Crashy" name="Crashy" type="variant">
    <arches>
      <arch>ppc64le</arch>
    </arches>
  </variant>

  <variant id="Gluster" name="Gluster Layered Product" type="layered-product">
    <release name="Gluster" version="2.3" short="Gluster" />
    <arches>
      <arch>x86_64</arch>
    </arches>
    <groups>
      <group default="true">gluster</group>
    </groups>
  </variant>

  <variant id="Client" name="Client" type="variant">
    <arches>
      <arch>i386</arch>
      <arch>x86_64</arch>
    </arches>
    <groups>
      <group default="true">core</group>
      <group default="true">standard</group>
      <group default="false">text-internet</group>
      <group default="true" uservisible="false">firefox</group>
      <group>skype</group>
    </groups>
    <environments>
      <environment>minimal</environment>
      <environment display_order="1000">desktop</environment>
    </environments>
  </variant>

  <variant id="Server" name="Server" type="variant" has_optional="true">
    <arches>
      <arch>x86_64</arch>
      <arch>s390x</arch>
    </arches>
    <groups>
      <group default="true" uservisible="true">core</group>
      <group default="true">standard</group>
      <group default="true">text-internet</group>
    </groups>
    <environments>
      <environment>minimal</environment>
    </environments>
    <variants>
      <ref id="ResilientStorage"/>
      <ref id="Gluster"/>
      <variant id="optional" name="optional" type="optional">
        <arches>
          <arch>x86_64</arch>
          <arch>s390x</arch>
        </arches>
        <groups>
          <group default="false">firefox</group>
        </groups>
      </variant>
    </variants>
  </variant>

</variants>
